eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9030
spring:
  application:
    name: comboservice1
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"