eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9040
spring:
  application:
    name: comboservice2
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"

