eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/dinner3000/springcloud-demo/
          searchPaths: configrepo
          username:
          password:
server:
  port: 8888
